config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :pins
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :pin

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pin.build
  end

  def edit
  end
  
  def create
    @pin = current_user.pin.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @pins = Pin.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/scaffold_helper.rb
module ScaffoldHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code4Andy</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <header>
    <div class="nav navbar-inverse navbar-fixed-top">
      <div class="container">
          <div class="nav-header navbar-brand">
            <a><%= link_to "Code4Andy" , root_path %></a>
          </div>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Search Pins</button>
          </form>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Inbox <span class="badge">42</span></a></li>
              <li><a href="#">Messages <span class="badge">4</span></a></li>
              <li><%= link_to "New Pin" , new_pin_path %></li>
              <li><%= link_to "Account" , edit_user_registration_path %></li>
              <li><%= link_to "Sign Out" , destroy_user_session_path , method: :delete %></li>
            </ul>
          <% else %>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign Up" , new_user_registration_path %></li>
              <li><%= link_to "Sign In " , new_user_session_path %></li>
          </ul>
          <% end %>  
        </div>
      </div>
    </header>
    <body><br><br><hr style="border: 0.5px solid #e9e9e9;">
  <div class="container"><br>
      <%= alert %></p>
      <%= yield %>
  </div>
  <footer class="footer">
         <p class="text-muted">Powered by : Code4Andy 2018</p>
       </footer>
 </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { mulitpart: true } do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>
      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
<div class="form-group"><%= f.input :image  %></div>
<div class="form-group"><%= f.input :title  %></div>
<div class="form-group"><%= f.input :description %></div>
  <%= f.submit :submit, class: "btn btn-primary" %>
<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Editing Pin</h2>
      </div>

		<div class="panel-body">
		  <strong class="center">Current Image</strong>
		  <br>
		  <%= image_tag @pin.image.url(:medium) %>
	    <div>
	      <%= render 'form', pin: @pin %>
	    </div>
	    <p><%= link_to 'Show', @pin %> |
	       <%= link_to 'Back', root_path %>
	    </p>
	  </div>
	</div>
  </div>
</div>

app/views/pins/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
   	<div class="panel-heading pin_image">
   	  <% @pins.each do |pin| %>
   	  <%= link_to (image_tag pin.image.url(:medium)), pin %>
	    <div class="panel-body">
		  <h2><%= link_to pin.title, pin %></h2>
  		  <p class="description"><%= pin.description %></p>
  		</div>
		  <div class="panel-footer">
		    <div class="row">
			 <div class="col-md-6">
			   <p class="user">Submitted by: <%= pin.user.email %></p>
			 </div>
			 <div class="col-md-6">
			  <div class="btn-group">
			   <div class="pull-right">	
				 <%= link_to 'Show', pin, class: "btn btn-default"%>  
				 <%= link_to 'Edit', edit_pin_path(pin), class: "btn btn-default" %> 
				 <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
			   </div> 
			  </div>
			 </div>
	  	    </div>
	  	   </div>
	  <% end %> 
	  </div>
	  </div>
	  </div>
</div>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>New Pin</h2>
      </div>
      <div class="panel-body">
	 	 <%= render 'form', pin: @pin %>
	  	 <%= link_to 'Back', root_path %>
	  </div>
	</div>
  </div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>
<div id="pin_show" class="row">
 <div class="col-md-8 col-md-offset-2">
   <div class="panel panel-default">
   	<div class="panel-heading pin_image">
		<%= image_tag @pin.image.url(:medium) %></div>
		<div class="panel-body">
			<h1><%= @pin.title %></h1>
  		<p class="description"><%= @pin.description %></p><br>
  		<p>Submitted by: <%= @pin.user.email %></p>
  		</div>
  	

		<div class="panel-footer">
			<div class="row">
				<div class="col-md-6">
					<p class="user">Submitted by: <%= @pin.user.email %></p>
				</div>
				<% if user_signed_in? %>
				<div class="col-md-6">
				  <div class="btn-group">
					<div class="pul-right">	
						<%= link_to 'Back', root_path, class: "btn btn-default"%>  
						<%= link_to 'Edit', edit_pin_path(@pin), class: "btn btn-default" %> 
						<%= link_to 'Delete', pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
					</div> 
				  </div>
			    </div>
			    <% end %>
			</div>
	  	</div>
	</div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="pins" class="transitions-enabled infinite-scroll clearfix">
  <% @pins.each do |pin| %>
  <div class="box ">
  	<div id="pin_show" class="pin_image">
		<%= link_to (image_tag pin.image.url), pin %>
	</div
	   <a href=""></a><h3><%= link_to pin.title, pin %></h3>
	   <div id="pins" class="user">
	  
	   </div>
  </div>
  <% end %>
</div>
</div>